\input texinfo    @c -*-texinfo-*-

@c %**start of header

@set VERSION 0.1.0-SNAPSHOT

@setfilename chrono.info
@settitle Chrono for Octave v@value{VERSION}
@documentencoding UTF-8

@c %**end of header

@copying
This manual is for Chrono, version @value{VERSION}.

Copyright @copyright{} 2019 Andrew Janke

@quotation
Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the same conditions as for modified versions.
@end quotation
@end copying

@documentdescription
User manual for Chrono for Octave.
@end documentdescription

@titlepage
@title  Chrono for Octave
@subtitle version @value{VERSION}, January 2019
@author Andrew Janke
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage


@contents

@ifnottex
@node Top, Introduction
@top Chrono for Octave

This manual is for Chrono, version @value{VERSION}.
@end ifnottex

@menu
* Introduction::
* Getting Started::
* Date Representation::
* Time Zones::
* Durations::
* Missing Functionality::
* Function Reference::
* Copying::
@end menu




@node Introduction
@chapter Introduction

@quotation
Time is an illusion. Lunchtime doubly so.

@author Douglas Adams
@end quotation

This is the manual for the Chrono package version @value{VERSION} for GNU Octave.

This document is a work in progress. You are invited to help improve it and
submit patches.

Chrono provides date/time functionality for Octave by supplying Matlab-compatible
implementations for the @code{datetime}, @code{duration}, and @code{calendarDuration}
classes, along with related functions.

Chrono's classes are designed to be convenient to use while still being efficient.
The data representations used by Chrono are designed to be efficient and suitable
for working with large-ish data sets. A “large-ish” data set is one that can have
millions of elements or rows, but still fits in main computer memory. Chrono's main
relational and arithmetic operations are all implemented using vectorized
operations on primitive Octave data types.

Chrono was written by Andrew Janke <@email{floss@@apjanke.net}>. Support can be
found on the @url{https://github.com/apjanke/octave-addons-chrono, Chrono project
GitHub page}.




@node Getting Started
@chapter Getting Started

The easiest way to obtain Chrono is by using Octave's @code{pkg} package manager. To
install the latest development (unstable) head of Chrono, run this in Octave:

@example
pkg install https://github.com/apjanke/octave-addons-chrono/archive/master.zip
@end example

Soon, once the code gets a bit more stable, numbered releases for Chrono will be
available, and you should use those instead.

For development, you can obtain the source code for Chrono from the project repo on GitHub at 
@url{https://github.com/apjanke/octave-addons-chrono}. Upon first installation, run
the @file{make_local} script to build the octfiles so Chrono will work. Then add the @file{inst} directory in the repo to your Octave path.




@node Date Representation
@chapter Date Representation

Chrono provides the `datetime` class for representing points in time.

@menu
* datetime Class::
@end menu

@node datetime Class
@section @code{datetime} Class

A @code{datetime} is an array object that represents points in time in the familiar
Gregorian calendar.

This is an attempt to reproduce the functionality of Matlab's @code{datetime}. It
also contains some Octave-specific extensions.

The underlying representation is that of a datenum (a @code{double}
containing the number of days since the Matlab epoch), but encapsulating it in an
object provides several benefits: friendly human-readable display, type safety,
automatic type conversion, and time zone support. In addition to the underlying
datenum array, a @code{datetime} inclues an optional @code{TimeZone} property 
indicating what time zone the datetimes are in.

@node datenum Compatibility
@subsection @code{datenum} Compatibility

While the underlying data representation of @code{datetime} is compatible with
(in fact, identical to) that of datenums, you cannot directly combine them
via assignment, concatenation, or most arithmetic operations.

This is because of the signature of the @code{datetime} constructor. When combining
objects and primitive types like @code{double}, the primitive type is promoted to an
object by calling the other object's one-argument constructor on it. However, the
one-argument numeric-input consstructor for @code{datetime} does not accept datenums:
it interprets its input as datevecs instead. This is due to a design decision on
Matlab's part; for compatibility, Octave does not alter that interface.

To combine @code{datetime}s with datenums, you can convert the datenums to @code{datetime}s
by calling @code{datetime.ofDatenum} or @code{datetime(x, 'ConvertFrom', 'datenum')}, or you
can convert the @code{datetime}s to datenums by accessing its @code{dnums} field with
@code{x.dnums}.

Examples:

@example
dt = datetime('2011-03-04')
dn = datenum('2017-01-01')
[dt dn]
    @result{} error: datenum: expected date vector containing [YEAR, MONTH, DAY, HOUR, MINUTE, SECOND]
[dt datetime.ofDatenum(dn)]
    @result{} 04-Mar-2011   01-Jan-2017
@end example




@node Time Zones
@chapter Time Zones

This section will describe Chrono's time zone support.

Chrono's time zone data is drawn from the @uref{https://www.iana.org/time-zones, 
IANA Time Zone Database}, also known as the “Olson Database”. Chrono includes a
copy of this database in its distribution so it can work on Windows, which does
not supply it like Unix systems do.



@node Durations
@chapter Durations

@menu
* duration Class::
* calendarDuration Class::
@end menu

@node duration Class
@section @code{duration} Class

This section will describe @code{duration}.

@node calendarDuration Class
@section @code{calendarDuration} Class

This section will describe @code{calendarDuration}.



@node Missing Functionality
@chapter Missing Functionality

Chrono is based on Matlab's date/time API and supports most of its major functionality.
But not all of it is implemented yet. The missing parts are currently:

@itemize
@item POSIX time zone support for years outside the IANA time zone database coverage
@item Week-of-year (ISO calendar) calculations
@item Various @code{'ConvertFrom'} forms for @code{datetime} and @code{duration}
@item Support for LDML formatting for @code{datetime}
@item Various functions: @code{between}, @code{caldiff}, @code{dateshift}, @code{week}
@item @code{isdst}, @code{isweekend}
@item @code{calendarDuration.split}
@item @code{duration.Format} support
@item @code{UTCOffset} and @code{DSTOffset} fields in the output of @code{timezones()}
@item Plotting support
@end itemize

It is the author's hope that all these will be implemented some day.






@node Function Reference
@chapter Function Reference

@iftex
@section Functions by Category
@subsection Date Representation
@table @asis
@item datetime
Represents points in time using the Gregorian calendar.
@item isdatetime
True if input is a `datetime' array, false otherwise.
@item NaT
“Not-a-Time”.
@end table
@subsection Durations
@table @asis
@item calendarDuration
Durations in time using variable-length calendar periods, such as days, months, and years, which may vary in length over time.
@item calmonths
Create a `calendarDuration' that is a given number of calendar months long.
@item calyears
Construct a `calendarDuration' a given number of years long.
@item days
Duration in days.
@item duration
Represents durations or periods of time as an amount of fixed-length time (i.e.
@item hours
Create a `duration' X hours long, or get the hours in a `duration' X.
@item isduration
True if input is a `duration' array, false otherwise.
@item milliseconds
Create a `duration' X milliseconds long, or get the milliseconds in a `duration' X.
@item minutes
Create a `duration' X hours long, or get the hours in a `duration' X.
@item seconds
Create a `duration' X seconds long, or get the seconds in a `duration' X.
@item timezones
List all the time zones defined on this system.
@item years
Create a `duration' X years long, or get the years in a `duration' X.
@end table
@end iftex


@section Functions Alphabetically
@menu
* NaT:: 	“Not-a-Time”.
* calendarDuration:: Durations in time using variable-length calendar
		periods, such as days, months, and years, which may vary in
		length over time.
* calmonths::	Create a `calendarDuration' that is a given number of
		calendar months long.
* calyears::	Construct a `calendarDuration' a given number of years
		long.
* datetime::	Represents points in time using the Gregorian calendar.
* days::	Duration in days.
* duration::	Represents durations or periods of time as an amount of
		fixed-length time (i.e.
* hours::	Create a `duration' X hours long, or get the hours in a
		`duration' X.
* isdatetime::	True if input is a `datetime' array, false otherwise.
* isduration::	True if input is a `duration' array, false otherwise.
* milliseconds:: Create a `duration' X milliseconds long, or get the
		milliseconds in a `duration' X.
* minutes::	Create a `duration' X hours long, or get the hours in a
		`duration' X.
* seconds::	Create a `duration' X seconds long, or get the seconds in a
		`duration' X.
* timezones::	List all the time zones defined on this system.
* years::	Create a `duration' X years long, or get the years in a
		`duration' X.
@end menu

@node NaT, calendarDuration, , Function Reference
@subsection NaT

@deftypefn {Function} {@var{out} =} NaT ()
@deftypefnx {Function} {@var{out} =} NaT (@var{sz})

“Not-a-Time”. Constructs a new @code{datetime} array of all @code{NaT} values of
the given size. If no input @var{sz} is given, the result is a scalar @code{NaT}.

@code{NaT} is the @code{datetime} equivalent of @code{NaN}. It represents a missing
or invalid value. @code{NaT} values never compare equal to, greater than, or less
than any value, including other @code{NaT}s. Doing arithmetic with a @code{NaT} and
any other value results in a @code{NaT}.

@end deftypefn



@node calendarDuration, calmonths, NaT, Function Reference
@subsection calendarDuration

@deftp {Class} calendarDuration

Durations in time using variable-length calendar periods, such as days,
months, and years, which may vary in length over time. (For example, a
calendar month may have 28, 30, or 31 days.)

@end deftp

@deftypefn {Constructor} {@var{obj} =} calendarDuration ()

Constructs a new scalar @code{calendarDuration} of zero elapsed time.

@end deftypefn

@deftypefn {Constructor} {@var{obj} =} calendarDuration (@var{Y}, @var{M}, @var{D})
@deftypefnx {Constructor} {@var{obj} =} calendarDuration (@var{Y}, @var{M}, @
  @var{D}, @var{H}, @var{MI}, @var{S})

Constructs new @code{calendarDuration} arrays based on input values.

@end deftypefn



@node calmonths, calyears, calendarDuration, Function Reference
@subsection calmonths

@deftypefn {Function File} {@var{out} =} calmonths (@var{x})
Create a @code{calendarDuration} that is a given number of calendar months
long.

Input @var{x} is a numeric array specifying the number of calendar months.

This is a shorthand alternative to calling the @code{calendarDuration}
constructor with @code{calendarDuration(0, x, 0)}.

Returns a new @code{calendarDuration} object of the same size as @var{x}.

@xref{calendarDuration}.

@end deftypefn



@node calyears, datetime, calmonths, Function Reference
@subsection calyears

@deftypefn {Function} {@var{out} =} calyears (@var{x})

Construct a @code{calendarDuration} a given number of years long.

This is a shorthand for calling @code{calendarDuration(@var{x}, 0, 0)}.

@xref{calendarDuration}.

@end deftypefn



@node datetime, days, calyears, Function Reference
@subsection datetime

@deftp {Class} datetime

Represents points in time using the Gregorian calendar.

The underlying values are doubles representing the number of days since the
Matlab epoch of "January 0, year 0". This has a precision of around nanoseconds
for typical times.

@end deftp

@deftypeivar datetime @code{double} dnums
The underlying datenums that represent the points in time.
@end deftypeivar

@deftypeivar datetime @code{char} TimeZone
The time zone this @code{datetime} array is in. Empty if this does not have a
time zone associated with it (“unzoned”). The name of an IANA time zone if
this does.
@end deftypeivar

@deftypeivar datetime @code{char} Format
The format to display this @code{datetime} in. Currently unsupported.
@end deftypeivar

@deftypefn {Constructor} {@var{obj} =} datetime ()

Constructs a new scalar @code{datetime} containing the current local time, with
no time zone attached.

@end deftypefn

@deftypefn {Constructor} {@var{obj} =} datetime (@var{datevec})
@deftypefnx {Constructor} {@var{obj} =} datetime (@var{datestrs})
@deftypefnx {Constructor} {@var{obj} =} datetime (@var{in}, @code{'ConvertFrom'}, @var{inType})
@deftypefnx {Constructor} {@var{obj} =} datetime @
  (@var{Y}, @var{M}, @var{D}, @var{H}, @var{MI}, @var{S})
@deftypefnx {Constructor} {@var{obj} =} datetime @
  (@var{Y}, @var{M}, @var{D}, @var{H}, @var{MI}, @var{MS})
@deftypefnx {Constructor} {@var{obj} =} datetime @
  (@dots{}, @code{'Format'}, @var{Format}, @code{'InputFormat'}, @var{InputFormat}, @
   @code{'Locale'}, @var{InputLocale}, @code{'PivotYear'}, @var{PivotYear}, @
   @code{'TimeZone'}, @var{TimeZone})

Constructs a new @code{datetime} array based on input values.

@end deftypefn



@node days, duration, datetime, Function Reference
@subsection days

@deftypefn {Function} {@var{out} =} days (@var{x})

Duration in days.

If @var{x} is numeric, then @var{out} is a @code{duration} array in units
of fixed-length 24-hour days, with the same size as @var{x}.

If @var{x} is a @code{duration}, then returns a @code{double} array the same
size as @var{x} indicating the number of fixed-length days that each duration
is.

@end deftypefn



@node duration, hours, days, Function Reference
@subsection duration

@deftp {Class} duration

Represents durations or periods of time as an amount of fixed-length
time (i.e. fixed-length seconds). It does not care about calendar things
like months and days that vary in length over time.

This is an attempt to reproduce the functionality of Matlab's @code{duration}. It
also contains some Octave-specific extensions.

@end deftp

@deftypefn {Constructor} {@var{obj} =} duration ()

Constructs a new scalar @code{duration} of zero elapsed time.

@end deftypefn

@deftypefn {Constructor} {@var{obj} =} duration (@var{durationstrs})
@deftypefnx {Constructor} {@var{obj} =} duration (@var{durationstrs}, @code{'InputFormat'}, @var{InputFormat})
@deftypefnx {Constructor} {@var{obj} =} duration (@var{H}, @var{MI}, @var{S})
@deftypefnx {Constructor} {@var{obj} =} duration (@var{H}, @var{MI}, @var{S}, @
  @var{MS})

Constructs a new @code{duration} array based on input values.

@end deftypefn



@node hours, isdatetime, duration, Function Reference
@subsection hours

@deftypefn {Function File} {@var{out} =} hours (@var{x})
Create a @code{duration} @var{x} hours long, or get the hours in a @code{duration}
@var{x}.

If input is numeric, returns a @code{duration} array that is that many hours in
time.

If input is a @code{duration}, converts the @code{duration} to a number of hours.

Returns an array the same size as @var{x}.
@end deftypefn



@node isdatetime, isduration, hours, Function Reference
@subsection isdatetime

@deftypefn {Function} {@var{tf} =} isdatetime (@var{x})

True if input is a @code{datetime} array, false otherwise.

Returns a logical array the same size as @var{x}.
@end deftypefn



@node isduration, milliseconds, isdatetime, Function Reference
@subsection isduration

@deftypefn {Function} {@var{tf} =} isduration (@var{x})

True if input is a @code{duration} array, false otherwise.

Returns a logical array the same size as @var{x}.
@end deftypefn



@node milliseconds, minutes, isduration, Function Reference
@subsection milliseconds

@deftypefn {Function File} {@var{out} =} milliseconds (@var{x})
Create a @code{duration} @var{x} milliseconds long, or get the milliseconds in a @code{duration}
@var{x}.

If input is numeric, returns a @code{duration} array that is that many milliseconds in
time.

If input is a @code{duration}, converts the @code{duration} to a number of milliseconds.

Returns an array the same size as @var{x}.
@end deftypefn



@node minutes, seconds, milliseconds, Function Reference
@subsection minutes

@deftypefn {Function File} {@var{out} =} hours (@var{x})
Create a @code{duration} @var{x} hours long, or get the hours in a @code{duration}
@var{x}.

@end deftypefn



@node seconds, timezones, minutes, Function Reference
@subsection seconds

@deftypefn {Function File} {@var{out} =} seconds (@var{x})
Create a @code{duration} @var{x} seconds long, or get the seconds in a @code{duration}
@var{x}.

If input is numeric, returns a @code{duration} array that is that many seconds in
time.

If input is a @code{duration}, converts the @code{duration} to a number of seconds.

Returns an array the same size as @var{x}.
@end deftypefn



@node timezones, years, seconds, Function Reference
@subsection timezones

@deftypefn {Function} {@var{out} =} timezones ()
@deftypefnx {Function} {@var{out} =} timezones (@var{area})

List all the time zones defined on this system.

This lists all the time zones that are defined in the IANA time zone database
used by this Octave. (On Linux and macOS, that will generally be the system
time zone database from @file{/usr/share/zoneinfo}. On Windows, it will be
the database redistributed with the Chrono package.

If the return is captured, the output is returned as a table if your Octave
has table support, or a struct if it does not. It will have fields/variables
containing column vectors:

@table @code
@item Name
The IANA zone name, as cellstr.
@item Area
The geographical area the zone is in, as cellstr.
@end table

Compatibility note: Matlab also includes UTCOffset and DSTOffset fields in
the output; these are currently unimplemented.

@end deftypefn



@node years, , timezones, Function Reference
@subsection years

@deftypefn {Function File} {@var{out} =} years (@var{x})
Create a @code{duration} @var{x} years long, or get the years in a @code{duration}
@var{x}.

If input is numeric, returns a @code{duration} array in units of fixed-length
years of 365.2425 days each.

If input is a @code{duration}, converts the @code{duration} to a number of fixed-length
years as double.

Note: @code{years} creates fixed-length years, which may not be what you want.
To create a duration of calendar years (which account for actual leap days),
use @code{calyears}.

@xref{calyears}.
@end deftypefn





@node Copying
@chapter Copying

@insertcopying

@bye
